import { Recipe, RecipeCategory, DietaryCategory } from '@/types/recipe'

export const sampleRecipes: Recipe[] = [
  {
    id: '1',
    title: 'Laks med asparges og cremet citronsmør',
    slug: 'laks-med-asparges-og-cremet-citronsmoer',
    description: 'Møre laksestykker serveret med sprøde asparges og en silkeblød citronsmørsauce med et hint af hvidløg og persille.',
    shortDescription: 'Møre laksestykker med sprøde asparges og cremet citronsmør',
    preparationTime: 15,
    cookingTime: 20,
    totalTime: 35,
    calories: 320,
    protein: 28,
    carbs: 8,
    fat: 22,
    fiber: 4,
    metaTitle: 'Laks med asparges og cremet citronsmør - Keto opskrift',
    metaDescription: 'Prøv denne lækre keto opskrift med laks og asparges. Nem at lave og perfekt til vægttab.',
    keywords: ['laks', 'asparges', 'keto', 'vægttab', 'aftensmad'],
    mainCategory: 'Aftensmad',
    subCategories: ['Familie mad', 'Nem hverdagsmad'],
    dietaryCategories: ['Keto', 'LCHF'],
    ingredients: [
      { id: '1', name: 'laksestykker', amount: 4, unit: 'stk' },
      { id: '2', name: 'asparges', amount: 500, unit: 'g' },
      { id: '3', name: 'smør', amount: 50, unit: 'g' },
      { id: '4', name: 'citron', amount: 1, unit: 'stk' },
      { id: '5', name: 'hvidløg', amount: 2, unit: 'fed' },
      { id: '6', name: 'persille', amount: 1, unit: 'bunke' },
    ],
    instructions: [
      { id: '1', stepNumber: 1, instruction: 'Forvarm ovnen til 200°C' },
      { id: '2', stepNumber: 2, instruction: 'Rens asparges og fjern de hårde ender' },
      { id: '3', stepNumber: 3, instruction: 'Steg laksen i en pande med lidt olie i 3-4 minutter på hver side' },
      { id: '4', stepNumber: 4, instruction: 'Kog asparges i let saltede vand i 3-4 minutter' },
      { id: '5', stepNumber: 5, instruction: 'Lav citronsmørsauce ved at smelte smør og tilføj citron, hvidløg og persille' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800&h=600&fit=crop',
    imageAlt: 'Laks med asparges og cremet citronsmør',
    servings: 4,
    difficulty: 'Nem',
    author: 'Functional Foods',
    publishedAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    rating: 4.8,
    reviewCount: 127,
    prepTimeISO: 'PT15M',
    cookTimeISO: 'PT20M',
    totalTimeISO: 'PT35M',
  },
  {
    id: '2',
    title: 'Blomkålsgratin med sprødt bacon',
    slug: 'blomkaalsgratin-med-sproedt-bacon',
    description: 'En cremet og velsmagende blomkålsgratin med sprødstegt bacon og ost, perfekt til hele familien på en kølig dansk aften.',
    shortDescription: 'Cremet blomkålsgratin med bacon og ost',
    preparationTime: 20,
    cookingTime: 30,
    totalTime: 50,
    calories: 450,
    protein: 25,
    carbs: 12,
    fat: 35,
    fiber: 6,
    metaTitle: 'Blomkålsgratin med sprødt bacon - Keto familie mad',
    metaDescription: 'Denne lækre blomkålsgratin er perfekt til hele familien og egner sig til keto og vægttab.',
    keywords: ['blomkål', 'bacon', 'gratin', 'keto', 'familie mad'],
    mainCategory: 'Aftensmad',
    subCategories: ['Familie mad', 'Gratin'],
    dietaryCategories: ['Keto', 'LCHF'],
    ingredients: [
      { id: '1', name: 'blomkål', amount: 1, unit: 'stk' },
      { id: '2', name: 'bacon', amount: 200, unit: 'g' },
      { id: '3', name: 'fløde', amount: 200, unit: 'ml' },
      { id: '4', name: 'revet ost', amount: 100, unit: 'g' },
      { id: '5', name: 'hvidløg', amount: 3, unit: 'fed' },
    ],
    instructions: [
      { id: '1', stepNumber: 1, instruction: 'Forvarm ovnen til 180°C' },
      { id: '2', stepNumber: 2, instruction: 'Del blomkålen i buketter og kog dem i 5 minutter' },
      { id: '3', stepNumber: 3, instruction: 'Steg bacon sprødt og hak det fint' },
      { id: '4', stepNumber: 4, instruction: 'Lav en cremet sauce med fløde, ost og hvidløg' },
      { id: '5', stepNumber: 5, instruction: 'Læg blomkål i en ildfast form og hæld sauce over' },
      { id: '6', stepNumber: 6, instruction: 'Top med bacon og ost, og bag i 25-30 minutter' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&h=600&fit=crop',
    imageAlt: 'Blomkålsgratin med sprødt bacon',
    servings: 6,
    difficulty: 'Mellem',
    author: 'Functional Foods',
    publishedAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
    rating: 4.6,
    reviewCount: 89,
    prepTimeISO: 'PT20M',
    cookTimeISO: 'PT30M',
    totalTimeISO: 'PT50M',
  },
  {
    id: '3',
    title: 'Kyllingebryst med grønne bønner',
    slug: 'kyllingebryst-med-groenne-boenner',
    description: 'Møre kyllingebryst serveret med friske grønne bønner og en let citronsauce. Perfekt til en sund hverdagsaften.',
    shortDescription: 'Møre kyllingebryst med grønne bønner og citronsauce',
    preparationTime: 10,
    cookingTime: 25,
    totalTime: 35,
    calories: 280,
    protein: 35,
    carbs: 15,
    fat: 12,
    fiber: 8,
    metaTitle: 'Kyllingebryst med grønne bønner - Sund aftensmad',
    metaDescription: 'Denne sunde opskrift med kylling og grønne bønner er perfekt til vægttab og en sund livsstil.',
    keywords: ['kylling', 'grønne bønner', 'sund mad', 'vægttab', 'aftensmad'],
    mainCategory: 'Aftensmad',
    subCategories: ['Nem hverdagsmad', 'Sund mad'],
    dietaryCategories: ['SENSE', 'KALORIETÆLLING'],
    ingredients: [
      { id: '1', name: 'kyllingebryst', amount: 4, unit: 'stk' },
      { id: '2', name: 'grønne bønner', amount: 400, unit: 'g' },
      { id: '3', name: 'citron', amount: 1, unit: 'stk' },
      { id: '4', name: 'olivenolie', amount: 2, unit: 'spsk' },
      { id: '5', name: 'hvidløg', amount: 2, unit: 'fed' },
      { id: '6', name: 'timian', amount: 1, unit: 'spsk' },
    ],
    instructions: [
      { id: '1', stepNumber: 1, instruction: 'Forvarm ovnen til 200°C' },
      { id: '2', stepNumber: 2, instruction: 'Krydr kyllingebrystene med salt, peber og timian' },
      { id: '3', stepNumber: 3, instruction: 'Steg kyllingen i en pande med olivenolie i 3-4 minutter på hver side' },
      { id: '4', stepNumber: 4, instruction: 'Bag kyllingen i ovnen i 15-20 minutter' },
      { id: '5', stepNumber: 5, instruction: 'Kog grønne bønner i let saltede vand i 3-4 minutter' },
      { id: '6', stepNumber: 6, instruction: 'Lav en let citronsauce med citron, hvidløg og olivenolie' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&h=600&fit=crop',
    imageAlt: 'Kyllingebryst med grønne bønner',
    servings: 4,
    difficulty: 'Nem',
    author: 'Functional Foods',
    publishedAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
    rating: 4.7,
    reviewCount: 156,
    prepTimeISO: 'PT10M',
    cookTimeISO: 'PT25M',
    totalTimeISO: 'PT35M',
  },
]

export const recipeCategories: RecipeCategory[] = [
  {
    id: '1',
    name: 'Aftensmad',
    slug: 'aftensmad',
    description: 'Sunde aftensmad opskrifter til vægttab',
    recipeCount: 1250,
  },
  {
    id: '2',
    name: 'Frokost',
    slug: 'frokost',
    description: 'Nemme og sunde frokost opskrifter',
    recipeCount: 890,
  },
  {
    id: '3',
    name: 'Morgenmad',
    slug: 'morgenmad',
    description: 'Energigivende morgenmad til en god start på dagen',
    recipeCount: 456,
  },
  {
    id: '4',
    name: 'Salater',
    slug: 'salater',
    description: 'Friske og sunde salater',
    recipeCount: 234,
  },
]

export const dietaryCategories: DietaryCategory[] = [
  {
    id: '1',
    name: 'KETO',
    slug: 'keto',
    description: 'Ketogene opskrifter til vægttab og sundhed',
    color: 'bg-purple-500',
    recipeCount: 712,
  },
  {
    id: '2',
    name: 'SENSE',
    slug: 'sense',
    description: 'Sunde opskrifter baseret på danske kostråd',
    color: 'bg-green-500',
    recipeCount: 445,
  },
  {
    id: '3',
    name: 'PALEO/LCHF',
    slug: 'paleo',
    description: 'Paleo og lav-kulhydrat opskrifter',
    color: 'bg-orange-500',
    recipeCount: 389,
  },
  {
    id: '4',
    name: 'INTERMITTEN FASTE',
    slug: 'intermittent-fasting',
    description: 'Opskrifter til intermittent fasting',
    color: 'bg-blue-500',
    recipeCount: 156,
  },
  {
    id: '5',
    name: 'KALORIETÆLLING',
    slug: 'kalorietaelling',
    description: 'Opskrifter med fokus på kalorieindhold',
    color: 'bg-red-500',
    recipeCount: 234,
  },
  {
    id: '6',
    name: 'MEALPREP',
    slug: 'mealprep',
    description: 'Opskrifter til madlavning på forhånd',
    color: 'bg-yellow-500',
    recipeCount: 189,
  },
  {
    id: '7',
    name: 'WHOLE30',
    slug: 'whole30',
    description: 'Whole30 kompatible opskrifter',
    color: 'bg-indigo-500',
    recipeCount: 123,
  },
] 