export { getDepartments, iterateAllRemaProducts } from './client'
export { mapRemaOffer, mapRemaProduct } from './mapper'
export { syncRema1000 } from './sync'
export type { RemaSyncOptions, RemaSyncResult } from './sync'
export type { RemaDepartment, RemaProduct } from './types'
